### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [HexagonalDiamond/pixelbuild#6]
Please add a free license :)

I suggest GPLv3!

**Comment by HexagonalDiamond** [comment]
Not sure if I want to do this yet since I'm still figuring out how I want it licensed. Thanks for the comment though!

**Comment by HexagonalDiamond** [comment]
I'm going to open source the client completely, but probably eventually close source the server, so I need to find the appropriate license. If you have any ideas, I'm not very educated on the licensing types. Also, if you want to contribute, it would be greatly appreciated. Thanks

**Comment by pizzamaker** [comment]
This might help you out: https://www.gnu.org/licenses/license-recommendations.html
